language: cpp
compiler: gcc
notifications:
  irc:
    channels:
      - "irc.blitzed.org#FeOS"
    skip_join: true
env:
  global:
    - DKA_TARBALL=devkitARM_r42-x86_64-linux.tar.bz2
    - DEVKITPRO=/opt/devkitpro
    - DEVKITARM=$DEVKITPRO/devkitARM
  matrix:
    - FEOSPLAT=rpi
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
install:
  - wget http://download.sourceforge.net/devkitpro/devkitARM/$DKA_TARBALL -O /tmp/$DKA_TARBALL
  - sudo mkdir -p $DEVKITPRO
  - sudo chmod 777 $DEVKITPRO
  - pushd $DEVKITPRO
  - tar -xvjf /tmp/$DKA_TARBALL
  - popd
script:
  - export FEOSSDK=$PWD/sdk
  - cd kernel
  - make
